"""Execution-distribution measurement primitives."""

from .backends import (
    GeneratedText,
    GenerationBackend,
    SequenceScoringBackend,
    SequenceTokenScores,
)
from .contracts import (
    AgentContext,
    Candidate,
    CandidateScore,
    ChatMessage,
    CheckpointPrefix,
    ContractError,
    GenerationConfig,
    GenerationRecord,
    LogitResult,
    MeasurementMethod,
    MeasurementRequest,
    SampledCandidate,
    SamplingResult,
    StructuredFormat,
)
from .formats import (
    CONTROL_ACTIONS,
    ActionSchema,
    FormatAdapter,
    FormatParseError,
    JSONFormatAdapter,
    OutputProtocol,
    ParseErrorCode,
    ParsedCandidate,
    XMLFormatAdapter,
    YAMLFormatAdapter,
    get_format_adapter,
    validate_decision,
)
from .scoring import (
    ScoringError,
    ScoringErrorCode,
    score_logit_distribution,
    stable_softmax,
)
from .projection import (
    ActionParameterDistribution,
    ActionProbability,
    ParameterCombinationProbability,
    ParameterMarginal,
    ParameterValueProbability,
    ProjectionError,
    ProjectionErrorCode,
    ProjectionResult,
    project_execution_distribution,
)
from .sampling import (
    SamplingError,
    SamplingErrorCode,
    sample_execution_distribution,
)
from .transformers_backend import (
    TransformersBackendError,
    TransformersBackendErrorCode,
    TransformersScoringBackend,
)
from .vllm_backend import (
    VLLMBackendError,
    VLLMBackendErrorCode,
    VLLMGenerationBackend,
    VLLMScoringBackend,
)

__all__ = [
    "ActionSchema",
    "ActionParameterDistribution",
    "ActionProbability",
    "AgentContext",
    "Candidate",
    "CandidateScore",
    "ChatMessage",
    "CheckpointPrefix",
    "ContractError",
    "CONTROL_ACTIONS",
    "GeneratedText",
    "GenerationBackend",
    "GenerationConfig",
    "GenerationRecord",
    "FormatAdapter",
    "FormatParseError",
    "JSONFormatAdapter",
    "LogitResult",
    "MeasurementMethod",
    "MeasurementRequest",
    "OutputProtocol",
    "ParameterCombinationProbability",
    "ParameterMarginal",
    "ParameterValueProbability",
    "ParseErrorCode",
    "ParsedCandidate",
    "ProjectionError",
    "ProjectionErrorCode",
    "ProjectionResult",
    "SampledCandidate",
    "SamplingResult",
    "SamplingError",
    "SamplingErrorCode",
    "ScoringError",
    "ScoringErrorCode",
    "SequenceScoringBackend",
    "SequenceTokenScores",
    "StructuredFormat",
    "TransformersBackendError",
    "TransformersBackendErrorCode",
    "TransformersScoringBackend",
    "VLLMBackendError",
    "VLLMBackendErrorCode",
    "VLLMGenerationBackend",
    "VLLMScoringBackend",
    "XMLFormatAdapter",
    "YAMLFormatAdapter",
    "get_format_adapter",
    "project_execution_distribution",
    "score_logit_distribution",
    "sample_execution_distribution",
    "stable_softmax",
    "validate_decision",
]
