"""Execution-distribution measurement primitives."""

from .backends import (
    GeneratedText,
    GenerationBackend,
    SequenceScoringBackend,
    SequenceTokenScores,
)
from .contracts import (
    AgentContext,
    Candidate,
    CandidateScore,
    ChatMessage,
    CheckpointPrefix,
    ContractError,
    GenerationConfig,
    GenerationRecord,
    LogitResult,
    MeasurementMethod,
    MeasurementRequest,
    SampledCandidate,
    SamplingResult,
    StructuredFormat,
)
from .formats import (
    CONTROL_ACTIONS,
    ActionSchema,
    FormatAdapter,
    FormatParseError,
    JSONFormatAdapter,
    OutputProtocol,
    ParseErrorCode,
    ParsedCandidate,
    XMLFormatAdapter,
    YAMLFormatAdapter,
    get_format_adapter,
    validate_decision,
)

__all__ = [
    "ActionSchema",
    "AgentContext",
    "Candidate",
    "CandidateScore",
    "ChatMessage",
    "CheckpointPrefix",
    "ContractError",
    "CONTROL_ACTIONS",
    "GeneratedText",
    "GenerationBackend",
    "GenerationConfig",
    "GenerationRecord",
    "FormatAdapter",
    "FormatParseError",
    "JSONFormatAdapter",
    "LogitResult",
    "MeasurementMethod",
    "MeasurementRequest",
    "OutputProtocol",
    "ParseErrorCode",
    "ParsedCandidate",
    "SampledCandidate",
    "SamplingResult",
    "SequenceScoringBackend",
    "SequenceTokenScores",
    "StructuredFormat",
    "XMLFormatAdapter",
    "YAMLFormatAdapter",
    "get_format_adapter",
    "validate_decision",
]
